Vagrant.configure("2") do |config|
  # uses ubuntu desktop 14.04 LTS
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  
  # port forward 8000 on the guest VM to localhost:8000 - mainly for convenience
  config.vm.network "forwarded_port", guest: 8000, host: 8000 #magento
  config.vm.network "forwarded_port", guest: 3306, host: 3306 #mysql
  config.vm.network "forwarded_port", guest: 9000, host: 9001 #xdebug

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "lamp.dev"  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
  
  proxy = ENV['HTTP_PROXY']
  config.vm.provision "shell", path: "./vagrant/provision.sh", :args => proxy
end
