Vagrant.configure("2") do |config|
  # p:\apps\software\vagrant boxes\lamp.dev.box
  config.vm.box = "lamp.dev"
  
  # port forward 8000 on the guest VM to localhost:8000 - mainly for convenience
  config.vm.network "forwarded_port", guest: 8000, host: 8000 #magento
  config.vm.network "forwarded_port", guest: 3306, host: 3307 #mysql
  
   
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "magento-vagrant-1.9.2.4"  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  config.trigger.after :up do
    run_remote "sudo service apache2 restart"
    #mount magento related files
    config.vm.synced_folder "./magento", "/var/www/html/magento"
  end
  
  config.vm.provision "shell", path: "./vagrant/provision.sh"
end
